//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Admission
    {
        public int Id { get; set; }
        public int PatientId { get; set; }
        public System.DateTime AdmissionDate { get; set; }
        public Nullable<System.DateTime> DischargeDate { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
