//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HospitalMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        public Doctor()
        {
            this.Visits = new HashSet<Visit>();
            this.Patients = new HashSet<Patient>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Office { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Address { get; set; }
        public int TypeOfDoctorId { get; set; }
    
        public virtual TypeOfDoctor TypeOfDoctor { get; set; }
        public virtual ICollection<Visit> Visits { get; set; }
        public virtual ICollection<Patient> Patients { get; set; }
    }
}
